line-length = 88

[lint]
ignore = [
  "T201",
  "PLC0414",
  "S101",
  "SLF001",
  "S311",
  "PLR2004",
  "TRY003",
  "EM101",
  "FBT001",
  "FBT002",
  "TC003",
  "S301",
]

[lint.isort]
known-first-party = ["chrysalis"]
