name: ci

on:
  push:

jobs:
  ruff:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          version: "latest"

      - name: Set up Python 3.13
        run: uv python install 3.13

      - name: Create virtual environment and install dependencies
        run: |
          uv venv --python 3.13
          source .venv/bin/activate
          uv sync --dev
      - name: Run ruff
        run: |
          uv run ruff format --check
          uv run ruff check
  mypy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          version: "latest"

      - name: Set up Python 3.13
        run: uv python install 3.13

      - name: Create virtual environment and install dependencies
        run: |
          uv venv --python 3.13
          uv sync --dev
      - name: Run mypy
        run: |
          uv run mypy .
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          version: "latest"

      - name: Set up Python 3.13
        run: uv python install 3.13

      - name: Create virtual environment and install dependencies
        run: |
          uv venv --python 3.13
          uv sync --dev
      - name: Run pytest with coverage
        run: |
          uv run pytest chrysalis
